### PR TITLE
Add Guix build

### PR DESCRIPTION
**Pull request by psolstice**
## PR intention
`gitian` build is hard to set up and often broken. Guix is superior option that is both easy and reliable

## Code changes brief
Code was copied from recent `bitcoin` (version 0.22). Build scripts were updated
Gitian scripts were updated as well but it won't always produce Linux executable that can run on pre-20.04 Ubuntu

### CODE REVIEW

**Review by levonpetrosyan93 — DISMISSED** [review]

**Comment by AaronFeickert** [comment]
The macOS build fails on an Ubuntu 21.10 variant.

**Comment by AaronFeickert** [comment]
All hosts build on an Ubuntu 21.10 variant.

**Comment by psolstice** [comment]
please check if after commit `da9b0ef3e830` output hashes are
```
2db88697128bbfa21488b70033ed40b04e80fff6dc018cae8df4c8fd32d65a6d  dist-archive/firo-da9b0ef3e830.tar.gz
67c361173c815af08eb347f8745dc22bf6c295da0d8817fd4aeafd487c254454  x86_64-apple-darwin19/firo-da9b0ef3e830-osx-unsigned.dmg
bae75a6d5f666c07010a50e2af4cda6c061e3556073e84356f539bfb72680720  x86_64-apple-darwin19/firo-da9b0ef3e830-osx-unsigned.tar.gz
5f973c26228bcad8e203e2ac732e29766145c2a745c9ea87af0a34db2203900c  x86_64-apple-darwin19/firo-da9b0ef3e830-osx64.tar.gz
2db88697128bbfa21488b70033ed40b04e80fff6dc018cae8df4c8fd32d65a6d  dist-archive/firo-da9b0ef3e830.tar.gz
7b84af3dde10742cf0036f9e1539afe7920180c5f43afcf6fd9cf6d47cb42084  x86_64-w64-mingw32/firo-da9b0ef3e830-win-unsigned.tar.gz
86542f03c0d2529a161fc909dade1293612d06d9e8a0b78c96fc14d0997da475  x86_64-w64-mingw32/firo-da9b0ef3e830-win64-debug.zip
766dce420a2e7c37f252f609b9dcdcffa93b9d786d95ebf34c36d1fc39321661  x86_64-w64-mingw32/firo-da9b0ef3e830-win64-setup-unsigned.exe
d99245025f9bd9b6b4863f5623ab7e2bc134bb0a5d4ba9d9b6a9c9ae7dff5dfc  x86_64-w64-mingw32/firo-da9b0ef3e830-win64.zip
2db88697128bbfa21488b70033ed40b04e80fff6dc018cae8df4c8fd32d65a6d  dist-archive/firo-da9b0ef3e830.tar.gz
149b903047e8c39667aa941b8aea50409d4a1940ff2a56287c70b90b32d359a6  x86_64-linux-gnu/firo-da9b0ef3e830-x86_64-linux-gnu-debug.tar.gz
8d7ab78fc9ee942b636441c06730398eff878b7df674f72d7256592cc3eb6657  x86_64-linux-gnu/firo-da9b0ef3e830-x86_64-linux-gnu.tar.gz
```

**Comment by AaronFeickert** [comment]
My hashes:
```
2db88697128bbfa21488b70033ed40b04e80fff6dc018cae8df4c8fd32d65a6d  dist-archive/firo-da9b0ef3e830.tar.gz
67c361173c815af08eb347f8745dc22bf6c295da0d8817fd4aeafd487c254454  x86_64-apple-darwin19/firo-da9b0ef3e830-osx-unsigned.dmg
bae75a6d5f666c07010a50e2af4cda6c061e3556073e84356f539bfb72680720  x86_64-apple-darwin19/firo-da9b0ef3e830-osx-unsigned.tar.gz
5f973c26228bcad8e203e2ac732e29766145c2a745c9ea87af0a34db2203900c  x86_64-apple-darwin19/firo-da9b0ef3e830-osx64.tar.gz
2db88697128bbfa21488b70033ed40b04e80fff6dc018cae8df4c8fd32d65a6d  dist-archive/firo-da9b0ef3e830.tar.gz
7b84af3dde10742cf0036f9e1539afe7920180c5f43afcf6fd9cf6d47cb42084  x86_64-w64-mingw32/firo-da9b0ef3e830-win-unsigned.tar.gz
86542f03c0d2529a161fc909dade1293612d06d9e8a0b78c96fc14d0997da475  x86_64-w64-mingw32/firo-da9b0ef3e830-win64-debug.zip
766dce420a2e7c37f252f609b9dcdcffa93b9d786d95ebf34c36d1fc39321661  x86_64-w64-mingw32/firo-da9b0ef3e830-win64-setup-unsigned.exe
d99245025f9bd9b6b4863f5623ab7e2bc134bb0a5d4ba9d9b6a9c9ae7dff5dfc  x86_64-w64-mingw32/firo-da9b0ef3e830-win64.zip
2db88697128bbfa21488b70033ed40b04e80fff6dc018cae8df4c8fd32d65a6d  dist-archive/firo-da9b0ef3e830.tar.gz
149b903047e8c39667aa941b8aea50409d4a1940ff2a56287c70b90b32d359a6  x86_64-linux-gnu/firo-da9b0ef3e830-x86_64-linux-gnu-debug.tar.gz
8d7ab78fc9ee942b636441c06730398eff878b7df674f72d7256592cc3eb6657  x86_64-linux-gnu/firo-da9b0ef3e830-x86_64-linux-gnu.tar.gz
```

**Comment by levonpetrosyan93** [comment]
My hashes the same.

**Comment by justanwar** [comment]
My hashes:
```
2db88697128bbfa21488b70033ed40b04e80fff6dc018cae8df4c8fd32d65a6d  dist-archive/firo-da9b0ef3e830.tar.gz
67c361173c815af08eb347f8745dc22bf6c295da0d8817fd4aeafd487c254454  x86_64-apple-darwin19/firo-da9b0ef3e830-osx-unsigned.dmg
bae75a6d5f666c07010a50e2af4cda6c061e3556073e84356f539bfb72680720  x86_64-apple-darwin19/firo-da9b0ef3e830-osx-unsigned.tar.gz
5f973c26228bcad8e203e2ac732e29766145c2a745c9ea87af0a34db2203900c  x86_64-apple-darwin19/firo-da9b0ef3e830-osx64.tar.gz
2db88697128bbfa21488b70033ed40b04e80fff6dc018cae8df4c8fd32d65a6d  dist-archive/firo-da9b0ef3e830.tar.gz
7b84af3dde10742cf0036f9e1539afe7920180c5f43afcf6fd9cf6d47cb42084  x86_64-w64-mingw32/firo-da9b0ef3e830-win-unsigned.tar.gz
86542f03c0d2529a161fc909dade1293612d06d9e8a0b78c96fc14d0997da475  x86_64-w64-mingw32/firo-da9b0ef3e830-win64-debug.zip
766dce420a2e7c37f252f609b9dcdcffa93b9d786d95ebf34c36d1fc39321661  x86_64-w64-mingw32/firo-da9b0ef3e830-win64-setup-unsigned.exe
d99245025f9bd9b6b4863f5623ab7e2bc134bb0a5d4ba9d9b6a9c9ae7dff5dfc  x86_64-w64-mingw32/firo-da9b0ef3e830-win64.zip
2db88697128bbfa21488b70033ed40b04e80fff6dc018cae8df4c8fd32d65a6d  dist-archive/firo-da9b0ef3e830.tar.gz
149b903047e8c39667aa941b8aea50409d4a1940ff2a56287c70b90b32d359a6  x86_64-linux-gnu/firo-da9b0ef3e830-x86_64-linux-gnu-debug.tar.gz
8d7ab78fc9ee942b636441c06730398eff878b7df674f72d7256592cc3eb6657  x86_64-linux-gnu/firo-da9b0ef3e830-x86_64-linux-gnu.tar.gz
```

**Comment by AaronFeickert** [comment]
> My hashes the same.

Can you post them directly?

**Comment by psolstice** [comment]
Hashes for commit `aa794c6aa9a494e9e7270b115b7c564d50bb3b69`:
```
2d4689b2b7f4346ae40e9527a3307daad5344acf471526e1ecf069268ce722e2  dist-archive/firo-aa794c6aa9a4.tar.gz
69e3ff28e957fd64686827088431ef5ca0a2e9959e8f82c0d787b4b6d66f8184  x86_64-apple-darwin19/firo-aa794c6aa9a4-osx-unsigned.dmg
b91500d612976a425a5e8c35f70eb853f96eb92fac54c6258b342499a5bfdca9  x86_64-apple-darwin19/firo-aa794c6aa9a4-osx-unsigned.tar.gz
cd7a0f322a6f016ca3f803b01842ecffbf6a8d516ceaac10ef6bebbc5d98fe44  x86_64-apple-darwin19/firo-aa794c6aa9a4-osx64.tar.gz
2d4689b2b7f4346ae40e9527a3307daad5344acf471526e1ecf069268ce722e2  dist-archive/firo-aa794c6aa9a4.tar.gz
095bcfb1842469d430186a360f8025327895989fef6991e15815be13b457e9ac  x86_64-w64-mingw32/firo-aa794c6aa9a4-win-unsigned.tar.gz
d3144069c78c5b5559fa2f855d2bfe94de1160bc53f07dfa1ca136d5f6292070  x86_64-w64-mingw32/firo-aa794c6aa9a4-win64-debug.zip
4f546d80a436d1f1f21592aa1f6343d6c059f223322be82bca44d53b590fea9b  x86_64-w64-mingw32/firo-aa794c6aa9a4-win64-setup-unsigned.exe
0d508486c0045a38c86afe00a894b1e798c17c7f129bc03c35d8b34395b0da51  x86_64-w64-mingw32/firo-aa794c6aa9a4-win64.zip
2d4689b2b7f4346ae40e9527a3307daad5344acf471526e1ecf069268ce722e2  dist-archive/firo-aa794c6aa9a4.tar.gz
4fbb76e0152130119fe63c0b68fd7ef7326600e663d5aed1d4954ac2162e53cf  x86_64-linux-gnu/firo-aa794c6aa9a4-x86_64-linux-gnu-debug.tar.gz
465c4cd3b30f09a26be747068da4daa4ca7eec8b6676ac05a80ae7f50d03d17d  x86_64-linux-gnu/firo-aa794c6aa9a4-x86_64-linux-gnu.tar.gz
```

**Comment by justanwar** [comment]
Hashes for commit `aa794c6`:
```
2d4689b2b7f4346ae40e9527a3307daad5344acf471526e1ecf069268ce722e2  dist-archive/firo-aa794c6aa9a4.tar.gz
69e3ff28e957fd64686827088431ef5ca0a2e9959e8f82c0d787b4b6d66f8184  x86_64-apple-darwin19/firo-aa794c6aa9a4-osx-unsigned.dmg
b91500d612976a425a5e8c35f70eb853f96eb92fac54c6258b342499a5bfdca9  x86_64-apple-darwin19/firo-aa794c6aa9a4-osx-unsigned.tar.gz
cd7a0f322a6f016ca3f803b01842ecffbf6a8d516ceaac10ef6bebbc5d98fe44  x86_64-apple-darwin19/firo-aa794c6aa9a4-osx64.tar.gz
2d4689b2b7f4346ae40e9527a3307daad5344acf471526e1ecf069268ce722e2  dist-archive/firo-aa794c6aa9a4.tar.gz
095bcfb1842469d430186a360f8025327895989fef6991e15815be13b457e9ac  x86_64-w64-mingw32/firo-aa794c6aa9a4-win-unsigned.tar.gz
d3144069c78c5b5559fa2f855d2bfe94de1160bc53f07dfa1ca136d5f6292070  x86_64-w64-mingw32/firo-aa794c6aa9a4-win64-debug.zip
4f546d80a436d1f1f21592aa1f6343d6c059f223322be82bca44d53b590fea9b  x86_64-w64-mingw32/firo-aa794c6aa9a4-win64-setup-unsigned.exe
0d508486c0045a38c86afe00a894b1e798c17c7f129bc03c35d8b34395b0da51  x86_64-w64-mingw32/firo-aa794c6aa9a4-win64.zip
2d4689b2b7f4346ae40e9527a3307daad5344acf471526e1ecf069268ce722e2  dist-archive/firo-aa794c6aa9a4.tar.gz
4fbb76e0152130119fe63c0b68fd7ef7326600e663d5aed1d4954ac2162e53cf  x86_64-linux-gnu/firo-aa794c6aa9a4-x86_64-linux-gnu-debug.tar.gz
465c4cd3b30f09a26be747068da4daa4ca7eec8b6676ac05a80ae7f50d03d17d  x86_64-linux-gnu/firo-aa794c6aa9a4-x86_64-linux-gnu.tar.gz
```

**Review by levonpetrosyan93 — DISMISSED** [review]

**Pull request merged**
