### PR TITLE
To support multiple inputs in Lelantus spend tx in Elysium

### PR DESCRIPTION
**Pull request by nopslide**
Increase to support multiple inputs in Lelantus spend tx in Elysium layer, due to with 4k, it will support only one spend input, which impractical to support multiple spend input in a spend tx.

### CODE REVIEW

**Review by a-bezrukov — APPROVED** [review]
I think we don't need an HF for increasing this size

**Review by psolstice — APPROVED** [review]

**Review by psolstice — CHANGES_REQUESTED** [review]
`elysium_build_tx_tests/wallettxbuilder_create_normal_b` is failing

**Comment by nopslide** [comment]
In the new version, I deleted class B transaction type, so this error from class B transaction tests will not be an issue

**Comment by sproxet** [comment]
This was merged into the elysium-lelantus branch in 6a740d535c0d41864863267f38eb0713a80d00a7.

**Pull request closed without merging**
