### PR TITLE
Update copyright ©️ in LicenseInfo ℹ️

### PR DESCRIPTION
**Pull request by KuroGuo**
There was a duplicate in the copyright :copyright: information and the year didn't match, I updated it. :beers:

image

image

### CODE REVIEW

**Comment by HysMagus** [comment]
Shouldn't this also have the DASH guys listed on the copyright?

**Comment by KuroGuo** [comment]
I don't think Dash should be listed because Dash is not Firo's dad :older_man:

**Comment by reubenyap** [comment]
Dash should be included because of the usage of their masternode infrastructure work.
The double mention was probably due to a find/replace when porting over masternode code.

**Comment by KuroGuo** [comment]
Added at the bottom.

`This product includes Masternodes software developed by the Dash Core
developers <https://www.dash.org>.
`

**Comment by HysMagus** [comment]
utACK

**Pull request merged**
